import { expect } from 'chai';
import { ethers } from 'hardhat';

import { ProveFactor, PlonkVerifier } from '../dist/typechain';

describe('Guess', () => {
  let verifier: PlonkVerifier;
  let prove: ProveFactor;

  // prove you know the factor of 8252987 without revealing the factor
  const question = 8252987;

  beforeEach(async () => {
    verifier = await (await ethers.getContractFactory('PlonkVerifier')).deploy() as PlonkVerifier;
    await verifier.deployed();

    prove = await (await ethers.getContractFactory('ProveFactor')).deploy(verifier.address, question) as ProveFactor;
    await prove.deployed();
  });

  it('submit calldata(generated by makefile) to prove you solve it', async () => {
    await expect(prove.prove('0x12f9d74f1024e77ed7eb353c4abce416ff60a0ab3d0ef3ffce0154a99764627320b2a60a3c8732b2db52f6a8ceb13275d551cee13d1c0ed1fd602c765cf30b310fdfd369d890e0c3ee98f11e7502e4368145aa3ab91c68de725fee89a588ec6917160e39dab43e59c371ac49d4e270064c37b6bfb3c7202742025346aa982e0b275585168dfd6e99788b19a4264730969831662aa1f43b34f818de70524b614527b694e8c546475e8129f8564ca985a36bd18f4528b86b137ef94890419dcd041c80fcf5bfa97160a9de87b604f87d865317c8343366c1149cac15d01abbfcbd234d37e704680fe64adca6e26332799ff65fa793d24a5d55749e20c827c339442720e363b2120946028141caa6ee3625849819a4dc278c185cce2400e59e755d10be7d9ac2a84d8f28c3ffcbd16ecd8061204b543b9b885d8f295e2467c605f321088cb9c0719f26d703fc90588a95e536ba4690b932d98f5a2dc5651d43a1e71dddc6c9f33010052c082a2ae41c88d1493c7816383775b8e17f986ccc88d0c9097e50ccc499a68c6aaf954aab85e69e1f6188fd16b0353c2a98e2b039bff7ab1d4c189b2e22c92923b802d824532fad3657942bfe22c40978d728eda47865a016ee2faa086936460b8d2a2d60beef4c59df413d30cc2960070138e3fa6b3a7109bb2c991a6d565189ba95b167e7cc97e2dbf0b0dfe96f781ec46ca9f468b10d0145d601bfa36f3c5d894d98658c552c015b6b415d5798c1b9144865987faf3f05a5a3320271846d4fde99cf023c514318c3a65ec9c2f82f35df156b8ec39a3b06af10813dca3327ed86c6c52bbd3222154cf726636e1f3c5b377a6f70d8f79102e2646552042f47e15e1a50549c56bc001dd0326cb7415f0ea6b8b1a8652d6b2fb2cc2e8fd7be14ea7cbeb92adf3744651ce949fe1a93d0fd42c158712ddbd9130008059d2102159e5eece920c3ea0387f2ead2e8d5e15eb9de4f3cad8e435001be7ce6be56d41ebe7cd6ca36fc59eba205be681f19a98f36a5ca50057caf9a27f8acdcbe2886e976863fb41e899c01339489e3c079e64d6a7cf6d6a57c05fb0ef86512d5320e919fb62e37591a27a425f7141fa116874155d2a476ecc059bb')).to.emit(prove, 'Solved');
  });
});
